# Generated by Django 2.2.13 on 2022-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_planet_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('Black', 'BLACK'), ('Brown', 'BROWN'), ('Yellow', 'YELLOW'), ('Red', 'RED'), ('Green', 'GREEN'), ('Purple', 'PURPLE'), ('Unknown', 'UNKNOWN')], default='Unknown', max_length=32),
        ),
    ]
