# Generated by Django 2.2.13 on 2022-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220205_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('Black', 'BLACK'), ('Brown', 'BROWN'), ('Blonde', 'BLONDE'), ('Red', 'RED'), ('White', 'WHITE'), ('Bald', 'BALD')], default='Bald', max_length=32),
        ),
    ]
